import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <nav
          style={{
            display: "flex",
            gap: "1rem",
            padding: "12px 20px",
            background: "#f5f5f5",
            borderBottom: "1px solid #ddd",
            marginBottom: "16px",
            fontSize: "15px",
          }}
        >
          <Link href="/recipes">Recipes</Link>
          <Link href="/storage">Storage</Link>
          <Link href="/products">Products</Link>
        </nav>

        {children}
        <Toaster />
      </body>
    </html>
  );
}
